name: Build and Redeploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout app
        uses: actions/checkout@v4

      - name: Checkout devops-toolkit
        uses: actions/checkout@v4
        with:
          repository: YourGitHubOrg/devops-toolkit
          path: devops-toolkit
          ref: v1.0.0

      # Login to registry (example)
      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build + push
        env:
          IMAGE_NAME: docker.io/lancer1977/api-documents
          DOCKERFILE_PATH: WebApi/Dockerfile
          CONTEXT_PATH: WebApi
          IMAGE_TAG: ${{ github.run_number }}
        run: |
          chmod +x devops-toolkit/scripts/docker/build_push.sh
          devops-toolkit/scripts/docker/build_push.sh

      - name: Portainer redeploy
        env:
          PORTAINER_WEBHOOK_URL: ${{ secrets.PORTAINER_WEBHOOK_URL }}
        run: |
          chmod +x devops-toolkit/scripts/portainer/redeploy.sh
          devops-toolkit/scripts/portainer/redeploy.sh
